### PR TITLE
Fix/rules fetch consolidation

### LINKED ISSUE #586: Rules - consolidate fetches
**Describe the issue**
On the Rules page, there are separate fetches for `my rules` and `all rules`, but this is unnecessary. We can consolidate them and filter the results by tab. We can also cache the results either in mem (with a useQuery, etc) or in indexedDB to prevent refetching unless the data is more than 10 minutes (or pick a number) stale as a good general practice for fetching less volatile data.

### PR DESCRIPTION
**Pull request by tjwdev**
This fixes #586

### CODE REVIEW

File: src/pages/tools/queryrules/Rules.js [hunk 1]
```diff
@@ -182,11 +185,12 @@ const Rules = props => {
 
   const fetchTableData = svc => {
```
Comment (gtasautumn) [inline src/pages/tools/queryrules/Rules.js:186]: I don't think we need this param anymore. We are only ever calling fetchTableData with the `rulesall` service, right? We can drop the param here and on the callers, and we can probably drop the service state var at the top.

Looks great otherwise. The fetching is much more efficient.

Comment (tjwdev) [reply src/pages/tools/queryrules/Rules.js:186]: You're right, I think it's removable.  It might even be that we don't need the service itself as a whole, but that's a different level of refactoring! I'll remove them here and push it up.

**Review by gtasautumn — APPROVED** [review]
looks good
