### PR TITLE
correct handling for bad paths

### LINKED ISSUE #562: Routing - unhandled endpoint requests do not redirect correctly
**Describe the bug**
When you enter an invalid uri, eg "/gtas/admin/sdfsdfs", the system loads a blank page.

**To Reproduce**
1. Login as admin
2. Enter an invalid admin endpoint into the browser and hit enter
3. Observe that the site serves a blank content page under the header
(See PR #640  for examples of endpoints to test)

**Expected behavior**
Invalid endpoints should trigger the 404 handler as it does elsewhere. Need to verify that all invalid endpoints are correctly handled.

**Screenshots**
Example of the 404 handler showing up correctly:

### PR DESCRIPTION
**Pull request by gtasautumn**
Cleanup handling for bad routes, fixes #562

Where the the path in a route has no landing page, any invalid nested route that's requested should result in the 404 page which shows the header and a message indicating that the requested resource is not correct. 

example paths that should return the 404 page:
```
https://[base_url]/gtas/foo
https://[base_url]/gtas/flights/foo
https://[base_url]/gtas/vetting/foo
https://[base_url]/gtas/paxDetail // missing required flight or pax id params
https://[base_url]/gtas/seat-chart  //missing any of the required flight or pax or seat params
```

For paths that **do** have a default landing page like Admin and Tools, rather than show the 404 page we redirect from an invalid path back up to the landing page because we have a default parent and it prevents urls with trailing slashes from loading a blank page.

example paths that redirect back up to the parent:
```
https://[base_url]/gtas/tools/foo  // redirects back to /gtas/tools
https://[base_url]/gtas/tools/watchlist/foo  // redirects back to /gtas/tools
https://[base_url]/gtas/admin/manageusers/foo  // redirects back to /gtas/admin
https://[base_url]/gtas/admin/foo  // redirects back to /gtas/admin
https://[base_url]/gtas/admin/   // trailing slash - redirects to /gtas/admin instead of showing a blank page
https://[base_url]/gtas/tools/    // trailing slash - redirects to /gtas/tools instead of showing a blank page

```

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -241,9 +248,10 @@ const App = props => {
                               roles={[ROLE.ADMIN, ROLE.WLMGR]}
                             >
                               <Watchlist path="/"></Watchlist>
-                              <Watchlist path="/:mode"></Watchlist>
+                              {NF404Default}
```
Comment (kasimhelil) [inline src/App.js:251]: `https://[base_url]/gtas/tools/watchlist/foo` returns a `404` page instead of the default page

**Review by kasimhelil — APPROVED** [review]
Tested it locally and looks good to me except `https://[base_url]/gtas/tools/watchlist/foo` returns to `404 page`
