### PR TITLE
Fixes/vetting

### LINKED ISSUE #146: Notify Users | formatting cleanup

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #146 #147 #149

### CODE REVIEW

File: src/components/countdownBadge/CountdownBadge.js [hunk 1]
```diff
@@ -37,6 +37,10 @@ const CountdownBadge = props => {
   const hours = !days ? parse(hrsraw) : pad(Math.abs(hrsraw));
   const minutes = !days && !hours ? parse(minraw, "00") : pad(Math.abs(minraw));
 
+  const formatedDays = days ? `${days}h` : days;
```
Comment (gtasautumn) [inline src/components/countdownBadge/CountdownBadge.js:40]: We can't hard-code the time-part abbreviations (h, m, s), because they only make sense in English. Let's verify with Dave, tho.
