### PR TITLE
Fix/username password validations

### LINKED ISSUE #762: Password Validation
**Describe the bug**
Inline Password validation tooltip doesn't work

**To Reproduce**
1. Go to `Admin -> Manage User`
2. Click on 'Add User Icon at the bottom right corner of the page'
3. Enter invalid password; e.g "pass"
4. Hover over on the red info icon next to the input box

**Expected behavior**
You should see the password constraints

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #762 #742 

- For signup request, I didn't add existing user validation since we shouldn't expose userIds before longing to the app. The user should hit submit button to see if that username is taken.

### CODE REVIEW

File: src/pages/admin/manageUsers/UserModal.js [hunk 1]
```diff
@@ -150,6 +147,25 @@ const UserModal = props => {
     return { valid: valid, info: <PasswordConstraints password={value} /> };
   };
 
+  const validateUsernameInput = (username = "") => {
+    const maxLen = 50;
```
Comment (gtasautumn) [inline src/pages/admin/manageUsers/UserModal.js:151]: Minor, but we should pull the max and min length constants into an enum in utils>constants. They are in use here and in signup.js. Otherwise, everything looks good.

File: src/pages/login/SignUp.js [hunk 2]
```diff
@@ -19,18 +19,53 @@ const SignUp = props => {
   const [displaySuccessMsg, setDisplaySuccessMsg] = useState(false);
   const [displayErrorMsg, setDisplayErrorMsg] = useState(false);
   const [locations, setLocations] = useState([]);
+  const USER_ID_TOO_SHORT = <Xl8 xid="um15">User ID is too short</Xl8>;
+  const USER_ID_TOO_LONG = <Xl8 xid="um15">User ID is too long</Xl8>;
```
Comment (gtasautumn) [inline src/pages/login/SignUp.js:23]: duplicate translation code um15

**Review by gtasautumn — APPROVED** [review]
looks good
