### PR TITLE
Fix duplicate api call

### LINKED ISSUE #91: PVL - duplicate API calls
The PVL grid is making multiple calls for the same data. It is calling **/users** and **/notetypes** and **/notes** for each record displayed in the grid when the page loads, which is expensive.

1. The call for user data should be made only once for the modal using it, not once per record in the table.
2. We should replace **/users** with an api to return only a list of  usernames since exposing other user information to non-admins is security concern.
3. We should make the call to **/notetypes** only once on this page (or once in the scope of the modal using it).
4. We should only fetch the **/notes** data when the modal is launched from a record to minimize unnecessary fetches.

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #91

### CODE REVIEW

File: src/pages/vetting/Vetting.js [hunk 1]
```diff
@@ -201,6 +216,33 @@ const Vetting = props => {
...
+          name: userEmail.email,
+          type: "checkbox",
+          checked: false
+        };
+      });
+      setUsersEmails(emails);
+    });
+  }, []);
+
+  useEffect(() => {
```
Comment (gtasautumn) [inline src/pages/vetting/Vetting.js:234]: Just fyi, because both of your useEffect fetches are running during the same conditions (same [] param), you could also include them in the same useEffect statement. It's good this way also tho, don't change it.

File: src/pages/vetting/review/Review.js [hunk 2]
```diff
@@ -128,7 +101,7 @@ const ReviewPVL = props => {
               placeholder="Choose note type"
               datafield="noteType"
               required="required"
-              options={notTypes}
+              options={props.notTypes}
```
Comment (gtasautumn) [inline src/pages/vetting/review/Review.js:104]: typo? should it be props.**noteTypes** ?
