### PR TITLE
Fix/pvl

### LINKED ISSUE #397: PVL - allow re-opened status
record action button should allow the user to re open a case
Action should not say reviewed when the status is already reviewed

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #397 #378 

- Separated review hit  add event note
- Now we can reopen reviewed hit from vetting page
- moved event note modal one folder up since it is used by paxdetails and vetting

### CODE REVIEW

File: src/utils/constants.js [hunk 1]
```diff
@@ -31,6 +31,12 @@ export const STATUS = {
   FAILURE: "FAILURE"
 };
 
+export const HIT_STATUS = {
+  REVIEWED: "Reviewed",
+  NEW: "New",
+  REOPENED: "Re_opened"
```
Comment (gtasautumn) [inline src/utils/constants.js:37]: It would be better to display "Re-opened" rather than the code we send back to save, but we can clean that up later. Ideally, the status codes would be int IDs on the backend.

**Review by gtasautumn — APPROVED** [review]
