### PR TITLE
Fix/manage user

### LINKED ISSUE #52: Admin Manage Users - Submission Field Validations
Password needs to have password confirmation. These fields need to validate pre-submit.

Email needs to validate pre-submit.

Must have at least 1 role selected.

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #52 #306 #341

### CODE REVIEW

File: src/pages/admin/manageUsers/UserModal.js [hunk 1]
```diff
@@ -108,13 +107,44 @@ const UserModal = props => {
...
+    );
+    let validPassword = true;
+    let validUserId = true;
+
+    if (!props.isEdit) {
+      validPassword = isValidPassword(res.password);
+      validUserId = !existingUserIds.includes(res.userId?.toUpperCase());
+    }
+    if (!validUserId) {
+      setAlertContent(INVALID_USER_ERROR);
```
Comment (gtasautumn) [inline src/pages/admin/manageUsers/UserModal.js:131]: nice.

**Review by gtasautumn — APPROVED** [review]
