### PR TITLE
Fixes for hit category default sort and date range values not passed

### LINKED ISSUE #596: PVL sorting needs different default sorting
**Describe the bug**
The current sorting is inadequate. Users login and the top-most records are not the best combination of severity and time-sensitivity.

**To Reproduce**
1. Create a rule that hits on everyone
2. Load data 
3. Go to PVL
4. See records that only sort by severity

**Expected behavior**
Apply two sorts to the default in this order
1. Priority (Most severe to least severe)
2. Countdown (soonest to latest)

### PR DESCRIPTION
**Pull request by tjwdev**
-Added init table state to table on vetting page
-Added sortBy array values, passing high cat variable name for back end sorting correctly
-datefilter/daterange are bundled as an array of values for props of the filter form
-This caused emergent bug that prevented children from having their datafields properly read when present
-Filterform modified to drill minimally 1 layer deeper seeking children in order to retrieve array for proper field assignment

The table should automatically sort the front-end now based on hit category AND the back end now receives a request with the appropriate sortBy filter.

Secondly, both data range and date picker should now properly make requests with their appropriate date ranges on the vetting page.

this fixes #596 and #760

### CODE REVIEW

**Comment by gtasautumn** [comment]
The sort looks good, but the filter values for the range and datetime are not being sent over. It appears to bind initially, but then get overwritten, so you always get the default date selections when you submit.

**Comment by tjwdev** [comment]
Failed to consider that the bug was more wide reaching. onChange event went untethered to the date filter fields because of the same reason they weren't getting included in the fields, i.e. they were in an array. Reworked the bind function a little to use the same technique under the init useEffect for the filter, it now digs for children. It also tracks a "trueIndex" since the parent child list can contain children-children, thus potentially throwing off the final array's actual key assignment for onChange event tethering.

File: src/components/filterForm2/FilterForm.js [hunk 1]
```diff
@@ -109,21 +109,38 @@ const FilterForm = props => {
...
-      // of FilterForm if needed.
-      delete cleanprops.callback;
-
-      return React.cloneElement(child, {
-        key: idx,
-        callback: onChange,
-        ...cleanprops
+    let trueIndex = 0;
+    let boundChildren = [];
+    asArray(props.children).forEach((child, idx) => {
```
Comment (gtasautumn) [inline src/components/filterForm2/FilterForm.js:114]: I think this should work, but can we extract this to a method? We are looping over the same collection both here and in the useEffect below. Also, we are not guarded against more deeply nested critters, which you pointed out earlier. No job is too small for recursion.

```
const getDatafieldsOnly = () => {
      let datafieldsonly = [];

    const recurse = coll => {
      asArray(coll).forEach(child => {
         if (child has datafield) datafieldsonly.push(child);
         if (has children) recurse(the children)
      }
    }

   recurse(props.children);
  return datafieldsonly;
}
```

that will put paid to any level of nesting we get later, and is easy to relocate to a util when we refactor this file to a more grokable size.

Other thing I am just noticing, am I calling bindChildren to catch changes to the form fields, like when the range and datetime fields swap out, or am I just calling it over and over for nothing? That's out of scope here, anyway. we can look at it later.

Comment (tjwdev) [reply src/components/filterForm2/FilterForm.js:114]: Yea, basically was thinking the same thing that both an external method and a recursive attempt that returns an array of child elements. I hadn't planned on it when I put the first one in, but it's now basically a duplicated (if slightly different) effort. I'll add the method and move the logic out of the internals either later tonight or tomorrow morning.

To answer your question to the best that I saw, my breakpoints weren't catch extra bindings during change events at all. onChange triggered, but no extraneous binds were going off. But when I'm adding the recursion I'll also do a double check at least to make sure there weren't excess calls.

Comment (tjwdev) [reply src/components/filterForm2/FilterForm.js]: Latest commit adds recursive function, although I did end up moving the function to utils but that's because I think we may run into similar problems in other areas potentially sooner than later and having it in a more universal spot I think might be better for us collectively. I hope that's alright.

**Review by gtasautumn — APPROVED** [review]
