### PR TITLE
Fix for multi-request vetting issue

### LINKED ISSUE #698: Vetting - fetch running 3 times on load
**Describe the issue**
The fetch for the grid data is re-running 3 times every time the page is loaded. Ran on dev and saw the duplicates each pull 300K of data (900K total). Need to change the logic for updating the filter form because currently it is rendering on load and also when the hit cats and note types load, which triggers the fetch. See ``cases.get()``

### PR DESCRIPTION
**Pull request by tjwdev**
Fixes #698 - Vetting fetch running 3 times on load
-Was calling on each list of categories being fetched rather than waiting for all data to be fetched, loaded, THEN make a request based on those parameters
-implemented hasData check for the types of categories, if both present THEN make call.
-removed init param request call since this is unnecessary since data is called AFTER init params are set based on table first time load anyway?
-Still extra call based on init param load, but this shaves requests down by 33%, there are solutions for the other. Will discuss before fixig.

### CODE REVIEW

File: src/pages/vetting/Vetting.js [hunk 1]
```diff
@@ -245,7 +245,7 @@ const Vetting = props => {
 
   const getInitialState = () => {
     setShowDateTimePicker(false);
-    setFilterFormKey(filterFormKey + 1);
```
Comment (gtasautumn) [inline src/pages/vetting/Vetting.js:248]: This line does generate a duplicate fetch, but removing it causes the date toggler to fall out of sync.

Comment (tjwdev) [reply src/pages/vetting/Vetting.js:248]: To fix the out of sync I was thinking of putting setShowDateTimePicker(false) after the hasData checks, since those are basically the initialParams being fully initialized themselves. That way I think that covers the asynchronous filter field loads now. 

If that's sufficient for that one aspect, that eliminates 1 request, however the initial call still triggers because it's the service for the model (before params loaded). I was planning on short-circuiting the get request if those params weren't present, but I ran into a small hiccup here since the model seems to expect a "then" function, which if I short circuit isn't going to necessarily be present.

**Comment by gtasautumn** [comment]
After some discussion, we decided to accept the current fix as a temporary measure. The final fix will involve refactoring the components to handle some basic update scheduling to ensure the fetch behavior is efficient and easily configured. That will be handled in a separate ticket.
