### PR TITLE
Fix/table no data rows

### LINKED ISSUE #767: Table - count = 1 when it should be 0
**Describe the bug**
The table is counting the "No data found" row as a result row. This happened during the most recent fix to the count when filtering the column headers was not causing the counts to adjust. Need to re-implement the test for the no data row.

### PR DESCRIPTION
**Pull request by gtasautumn**
fixes #767. Two issues

1. The default row that says "No Data Found" is causing the table row count to show 1 instead of 0.
2. The Table component has a circular dependency between a state var called data and ``parseData()``, where a useEffect on ``data`` calls ``parseData()``, which again updates ``data``. The logic is messy and fragile, needs refacking. Have fixed the loop, but will need to address additional issues here or in another ticket.

tableNoDataFoundCount

### CODE REVIEW

File: src/components/table/table-utils.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
+// All GTAS code is Copyright 2016, The Department of Homeland Security (DHS), U.S. Customs and Border Protection (CBP).
+//
+// Please see license.txt for details.
+
```
Comment (kasimhelil) [inline src/components/table/table-utils.js:4]: React needs to e import here

I am getting the following error
_```
src/components/table/table-utils.js
  Line 9:5:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 21:5:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 28:7:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 29:7:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 30:7:  'React' must be in scope when using JSX  react/react-in-jsx-scope
```_

**Review by kasimhelil — APPROVED** [review]
